import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useMemo, useRef, useState } from "react";
import { Download, Loader2, Search } from "lucide-react";
import { toast } from "sonner";
import { PageHeader } from "@/components/AppShell";
import { AlysonBrainDashboardView } from "@/components/AlysonBrainDashboard";
import {
  fetchAlysonBrainDashboard,
  fetchAlysonBrainInsights,
  fetchAlysonBrainSlowData,
  type AlysonBrainDashboardPayload,
  type AlysonBrainInsights,
} from "@/lib/alyson-brain-functions";
import { downloadAlysonBrainPdf } from "@/lib/alyson-brain-pdf";
import {
  loadAlysonBrainSession,
  readAlysonBrainSnapshot,
  saveAlysonBrainSession,
} from "@/lib/alyson-brain-session";

export const Route = createFileRoute("/alyson-brain")({
  head: () => ({ meta: [{ title: "Alyson Brain — Alyson HR" }] }),
  component: AlysonBrainPage,
});

const SUGGESTIONS = [
  "Report on Thirumalai for past 3 months",
  "Bhupen and Mohita for last 90 days",
  "Summary for Thiru — leaves, bonus, pacing and meetings",
];

function AlysonBrainPage() {
  const boot = useMemo(() => {
    const session = loadAlysonBrainSession();
    const snapshot = session ? readAlysonBrainSnapshot(session.question) : undefined;
    return { session, snapshot };
  }, []);

  const [input, setInput] = useState(boot.session?.inputDraft ?? boot.session?.question ?? "");
  const [question, setQuestion] = useState(boot.snapshot?.question ?? boot.session?.question ?? "");
  const [dashboard, setDashboard] = useState<AlysonBrainDashboardPayload | null>(
    boot.snapshot?.dashboard ?? null,
  );
  const [insights, setInsights] = useState<AlysonBrainInsights | null>(boot.snapshot?.insights ?? null);
  const [fastLoading, setFastLoading] = useState(false);
  const [insightsLoading, setInsightsLoading] = useState(false);
  const [slowLoadingByEmail, setSlowLoadingByEmail] = useState<Record<string, boolean>>({});
  const restoredRef = useRef(Boolean(boot.snapshot?.dashboard));
  const insightsRef = useRef(insights);
  insightsRef.current = insights;

  const persist = (
    next: {
      question?: string;
      inputDraft?: string;
      dashboard?: AlysonBrainDashboardPayload | null;
      insights?: AlysonBrainInsights | null;
    } = {},
  ) => {
    const q = next.question ?? question;
    const d = next.dashboard !== undefined ? next.dashboard : dashboard;
    const ins = next.insights !== undefined ? next.insights : insights;
    if (!q.trim() || !d) return;
    saveAlysonBrainSession({
      question: q,
      inputDraft: next.inputDraft ?? input,
      dashboard: d,
      insights: ins,
    });
  };

  useEffect(() => {
    if (restoredRef.current && boot.snapshot?.dashboard) {
      restoredRef.current = false;
      toast.message("Restored your last Alyson Brain report");
    }
  }, [boot.snapshot?.dashboard]);

  const runReport = async (text?: string) => {
    const q = (text ?? input).trim();
    if (!q || fastLoading) return;
    setInput(q);
    setQuestion(q);
    setDashboard(null);
    setInsights(null);
    setSlowLoadingByEmail({});
    setFastLoading(true);
    setInsightsLoading(true);

    try {
      const fast = await fetchAlysonBrainDashboard({ data: { question: q } });
      setDashboard(fast);
      setFastLoading(false);
      persist({ question: q, inputDraft: q, dashboard: fast, insights: null });
      toast.success("Dashboard ready", {
        description: fast.employees.map((e) => e.employee.displayName).join(", ") || "Loading modules…",
      });

      void fetchAlysonBrainInsights({ data: { question: q } })
        .then((ins) => {
          setInsights(ins);
          persist({ question: q, dashboard: fast, insights: ins });
          toast.success("Report generated by Alyson Brain");
        })
        .catch(() => {
          const fallback: AlysonBrainInsights = {
            narrative: "Insights unavailable.",
            provider: "none",
            model: "none",
            generatedAt: new Date().toISOString(),
          };
          setInsights(fallback);
          persist({ question: q, dashboard: fast, insights: fallback });
        })
        .finally(() => setInsightsLoading(false));

      for (const emp of fast.employees) {
        if (!emp.employee.email) continue;
        const email = emp.employee.email;
        setSlowLoadingByEmail((prev) => ({ ...prev, [email]: true }));
        void fetchAlysonBrainSlowData({ data: { question: q, email } })
          .then((slow) => {
            setDashboard((prev) => {
              if (!prev) return prev;
              const merged = {
                ...prev,
                employees: prev.employees.map((e) =>
                  e.employee.email === email ? { ...e, meetings: slow.meetings, tasks: slow.tasks } : e,
                ),
              };
              persist({ question: q, dashboard: merged, insights: insightsRef.current });
              return merged;
            });
          })
          .finally(() => setSlowLoadingByEmail((prev) => ({ ...prev, [email]: false })));
      }
    } catch (e) {
      const msg = e instanceof Error ? e.message : "Failed to load dashboard";
      toast.error("Alyson Brain error", { description: msg });
      setFastLoading(false);
      setInsightsLoading(false);
    }
  };

  const hasReport = Boolean(dashboard);

  return (
    <div className="ops-dense min-h-[calc(100vh-4rem)]">
      <PageHeader
        eyebrow="Intelligence"
        title="Alyson Brain"
        description="Ask about an employee in plain language. Alyson pulls scoring, hours, workspace, leave, bonus, meetings, and tasks into one report."
        actions={
          hasReport && !fastLoading ? (
            <button
              type="button"
              onClick={() => downloadAlysonBrainPdf({ dashboard: dashboard!, insights, question })}
              className="inline-flex h-9 items-center gap-2 rounded-md border border-border bg-background px-3 text-[13px] font-medium transition hover:bg-muted/50"
            >
              <Download className="h-3.5 w-3.5" />
              Download PDF
            </button>
          ) : undefined
        }
      />

      <div className="mx-auto max-w-4xl app-page-gutter py-6 space-y-8">
        <div className="space-y-3">
          <form
            className="flex flex-col gap-2 sm:flex-row"
            onSubmit={(e) => {
              e.preventDefault();
              void runReport();
            }}
          >
            <div className="relative flex-1">
              <Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
              <input
                value={input}
                onChange={(e) => setInput(e.target.value)}
                disabled={fastLoading}
                placeholder="Report on Thirumalai for past 3 months"
                className="h-10 w-full rounded-md border border-border bg-background pl-9 pr-3 text-[13px] outline-none ring-ring/30 transition focus:ring-2 disabled:opacity-60"
              />
            </div>
            <button
              type="submit"
              disabled={fastLoading || !input.trim()}
              className="inline-flex h-10 shrink-0 items-center justify-center rounded-md bg-foreground px-5 text-[13px] font-medium text-background transition hover:opacity-90 disabled:opacity-40"
            >
              {fastLoading ? <Loader2 className="h-4 w-4 animate-spin" /> : "Generate report"}
            </button>
          </form>

          {!hasReport && !fastLoading && (
            <div className="flex flex-wrap gap-2">
              {SUGGESTIONS.map((s) => (
                <button
                  key={s}
                  type="button"
                  onClick={() => void runReport(s)}
                  className="rounded-md border border-border bg-muted/30 px-2.5 py-1 text-[12px] text-muted-foreground transition hover:bg-muted/60 hover:text-foreground"
                >
                  {s}
                </button>
              ))}
            </div>
          )}
        </div>

        {fastLoading && !dashboard && (
          <div className="surface-card flex flex-col items-center gap-4 py-16 text-center">
            <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
            <div>
              <p className="text-[13px] font-medium">Building report</p>
              <p className="mt-1 text-[12px] text-muted-foreground">
                Loading scoring, hours, pacing, leave, and bonus…
              </p>
            </div>
          </div>
        )}

        {dashboard && (
          <AlysonBrainDashboardView
            dashboard={dashboard}
            insights={insights}
            insightsLoading={insightsLoading}
            slowLoadingByEmail={slowLoadingByEmail}
            question={question}
          />
        )}

        {!hasReport && !fastLoading && (
          <div className="surface-card px-6 py-14 text-center">
            <img src="/images/alyson-mini.svg" alt="" className="mx-auto mb-4 h-12 w-12 opacity-80" />
            <p className="font-display text-lg font-semibold">Employee intelligence, one question away</p>
            <p className="mx-auto mt-2 max-w-md text-[13px] leading-relaxed text-muted-foreground">
              Type a name and time range above. Results appear as a structured dashboard — not a chat
              transcript.
            </p>
          </div>
        )}
      </div>
    </div>
  );
}
