import type { MeetingListPersonTasks, MeetingListTask } from "@/lib/notetaker-meeting-ui";

function taskStatusLabel(status: MeetingListTask["status"]) {
  if (status === "done") return "Done";
  if (status === "unclear") return "Unclear";
  return "Open";
}

function taskStatusClass(status: MeetingListTask["status"]) {
  if (status === "done") return "text-emerald-700 bg-emerald-50 border-emerald-200";
  if (status === "unclear") return "text-amber-700 bg-amber-50 border-amber-200";
  return "text-foreground bg-muted/40 border-border";
}

export function MeetingTasksPanel({
  people,
  model,
  fromS3,
}: {
  people: MeetingListPersonTasks[];
  model?: string;
  fromS3?: boolean;
}) {
  if (people.length === 0) {
    return (
      <p className="text-[12px] text-muted-foreground leading-relaxed font-sans">
        No action items found for participants in this meeting.
      </p>
    );
  }

  return (
    <div className="flex flex-col gap-2 font-sans">
      <div className="flex flex-col gap-3">
        {people.map((person) => (
          <div key={person.personKey} className="rounded-md border border-border bg-background overflow-hidden">
            <div className="px-2.5 py-2 border-b border-border/60 bg-muted/30">
              <div className="text-[12px] font-medium text-foreground">{person.name}</div>
              {person.email && (
                <div className="text-[10.5px] text-muted-foreground mt-0.5">{person.email}</div>
              )}
            </div>
            <ul className="divide-y divide-border/60">
              {person.tasks.map((task, idx) => (
                <li key={`${person.personKey}-${idx}`} className="px-2.5 py-2">
                  <div className="flex flex-wrap items-start justify-between gap-2">
                    <span className="text-[12px] text-foreground leading-snug">{task.title}</span>
                    <div className="flex items-center gap-1 shrink-0">
                      <span
                        className={
                          "rounded-full border px-1.5 py-0.5 text-[10px] font-medium " +
                          taskStatusClass(task.status)
                        }
                      >
                        {taskStatusLabel(task.status)}
                      </span>
                      <span className="rounded-full border border-border px-1.5 py-0.5 text-[10px] text-muted-foreground capitalize">
                        {task.priority}
                      </span>
                    </div>
                  </div>
                  {(task.dueHint || task.sourceQuote) && (
                    <p className="mt-1 text-[10.5px] text-muted-foreground leading-relaxed">
                      {task.dueHint ? `Due: ${task.dueHint}` : null}
                      {task.dueHint && task.sourceQuote ? " · " : null}
                      {task.sourceQuote ? `“${task.sourceQuote}”` : null}
                    </p>
                  )}
                </li>
              ))}
            </ul>
          </div>
        ))}
      </div>
      {model && (
        <p className="text-[10.5px] text-muted-foreground">
          {fromS3 ? `Loaded from S3 · model ${model}` : `Generated by ${model}`}
        </p>
      )}
    </div>
  );
}
