/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceActivityRouteImport } from './routes/workspace-activity'
import { Route as WorkflowsRouteImport } from './routes/workflows'
import { Route as TimeDashboardRouteImport } from './routes/time-dashboard'
import { Route as TeamRouteImport } from './routes/team'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PerformanceRouteImport } from './routes/performance'
import { Route as PayrollRouteImport } from './routes/payroll'
import { Route as HelpRouteImport } from './routes/help'
import { Route as HandoverDocumentationRouteImport } from './routes/handover-documentation'
import { Route as EquityRouteImport } from './routes/equity'
import { Route as EmployeeScoringRouteImport } from './routes/employee-scoring'
import { Route as EmployeeOnboardingRouteImport } from './routes/employee-onboarding'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as BoardingRouteImport } from './routes/boarding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as AppRouteImport } from './routes/app'
import { Route as AlysonBrainRouteImport } from './routes/alyson-brain'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LeaveRouteRouteImport } from './routes/leave/route'
import { Route as BonusRouteRouteImport } from './routes/bonus/route'
import { Route as AlysonNotetakerRouteRouteImport } from './routes/alyson-notetaker/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LeaveIndexRouteImport } from './routes/leave/index'
import { Route as BonusIndexRouteImport } from './routes/bonus/index'
import { Route as AlysonNotetakerIndexRouteImport } from './routes/alyson-notetaker/index'
import { Route as WorkspaceActivityUserEmailRouteImport } from './routes/workspace-activity.$userEmail'
import { Route as WebhooksRecallRouteImport } from './routes/webhooks/recall'
import { Route as TimeDashboardPacingRouteImport } from './routes/time-dashboard.pacing'
import { Route as TimeDashboardMonthlyPacingRouteImport } from './routes/time-dashboard.monthly-pacing'
import { Route as TimeDashboardUserIdRouteImport } from './routes/time-dashboard.$userId'
import { Route as LeaveCalendarRouteImport } from './routes/leave/calendar'
import { Route as LeaveAuditRouteImport } from './routes/leave/audit'
import { Route as LeaveAnalyticsRouteImport } from './routes/leave/analytics'
import { Route as EmployeeScoringUserEmailRouteImport } from './routes/employee-scoring.$userEmail'
import { Route as BonusSimulateRouteImport } from './routes/bonus/simulate'
import { Route as BonusPlansRouteImport } from './routes/bonus/plans'
import { Route as BonusAuditRouteImport } from './routes/bonus/audit'
import { Route as BonusApprovalsRouteImport } from './routes/bonus/approvals'
import { Route as BonusAnalyticsRouteImport } from './routes/bonus/analytics'
import { Route as AlysonNotetakerUnifiedMeetingsRouteImport } from './routes/alyson-notetaker/unified-meetings'
import { Route as AlysonNotetakerTasksRouteImport } from './routes/alyson-notetaker/tasks'
import { Route as AlysonNotetakerMeetingListRouteImport } from './routes/alyson-notetaker/meeting-list'
import { Route as AlysonNotetakerCostTrackingRouteImport } from './routes/alyson-notetaker/cost-tracking'
import { Route as AlysonNotetakerCalendarRouteImport } from './routes/alyson-notetaker/calendar'
import { Route as AlysonNotetakerBotJoinReportRouteImport } from './routes/alyson-notetaker/bot-join-report'
import { Route as AlysonNotetakerAnalyticsRouteImport } from './routes/alyson-notetaker/analytics'
import { Route as ApiCronTimeDoctorTokenRouteImport } from './routes/api/cron/time-doctor-token'
import { Route as ApiCronScheduledBotActivationRouteImport } from './routes/api/cron/scheduled-bot-activation'
import { Route as ApiCronRecallCalendarSyncRouteImport } from './routes/api/cron/recall-calendar-sync'
import { Route as ApiCronNotetakerTranscriptsRouteImport } from './routes/api/cron/notetaker-transcripts'
import { Route as ApiCronDailyReportsRouteImport } from './routes/api/cron/daily-reports'
import { Route as ApiAnalyticsWorkspaceActivityRouteImport } from './routes/api/analytics/workspace-activity'
import { Route as ApiAnalyticsUnifiedMeetingsRouteImport } from './routes/api/analytics/unified-meetings'
import { Route as ApiAnalyticsEmployeeScoringRouteImport } from './routes/api/analytics/employee-scoring'
import { Route as AlysonNotetakerAnalyticsUnifiedMeetingsRouteImport } from './routes/alyson-notetaker/analytics.unified-meetings'
import { Route as ApiRecallWebhooksCalendarRouteImport } from './routes/api/recall/webhooks/calendar'
import { Route as ApiRecallCalendarStatusRouteImport } from './routes/api/recall/calendar/status'
import { Route as ApiRecallCalendarConnectRouteImport } from './routes/api/recall/calendar/connect'
import { Route as ApiRecallCalendarCallbackRouteImport } from './routes/api/recall/calendar/callback'
import { Route as ApiAnalyticsWorkspaceActivityUserEmailRouteImport } from './routes/api/analytics/workspace-activity.$userEmail'
import { Route as ApiAnalyticsUnifiedMeetingsScheduleBotsRouteImport } from './routes/api/analytics/unified-meetings.schedule-bots'
import { Route as ApiAnalyticsUnifiedMeetingsRefreshRouteImport } from './routes/api/analytics/unified-meetings.refresh'
import { Route as ApiAnalyticsEmployeeScoringUserEmailRouteImport } from './routes/api/analytics/employee-scoring.$userEmail'
import { Route as ApiAnalyticsUnifiedMeetingsMeetingIdUnscheduleRouteImport } from './routes/api/analytics/unified-meetings.$meetingId.unschedule'
import { Route as ApiAnalyticsUnifiedMeetingsMeetingIdScheduleRouteImport } from './routes/api/analytics/unified-meetings.$meetingId.schedule'

const WorkspaceActivityRoute = WorkspaceActivityRouteImport.update({
  id: '/workspace-activity',
  path: '/workspace-activity',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsRoute = WorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const TimeDashboardRoute = TimeDashboardRouteImport.update({
  id: '/time-dashboard',
  path: '/time-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceRoute = PerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const PayrollRoute = PayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const HandoverDocumentationRoute = HandoverDocumentationRouteImport.update({
  id: '/handover-documentation',
  path: '/handover-documentation',
  getParentRoute: () => rootRouteImport,
} as any)
const EquityRoute = EquityRouteImport.update({
  id: '/equity',
  path: '/equity',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeScoringRoute = EmployeeScoringRouteImport.update({
  id: '/employee-scoring',
  path: '/employee-scoring',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeOnboardingRoute = EmployeeOnboardingRouteImport.update({
  id: '/employee-onboarding',
  path: '/employee-onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardingRoute = BoardingRouteImport.update({
  id: '/boarding',
  path: '/boarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AlysonBrainRoute = AlysonBrainRouteImport.update({
  id: '/alyson-brain',
  path: '/alyson-brain',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaveRouteRoute = LeaveRouteRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => rootRouteImport,
} as any)
const BonusRouteRoute = BonusRouteRouteImport.update({
  id: '/bonus',
  path: '/bonus',
  getParentRoute: () => rootRouteImport,
} as any)
const AlysonNotetakerRouteRoute = AlysonNotetakerRouteRouteImport.update({
  id: '/alyson-notetaker',
  path: '/alyson-notetaker',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaveIndexRoute = LeaveIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LeaveRouteRoute,
} as any)
const BonusIndexRoute = BonusIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BonusRouteRoute,
} as any)
const AlysonNotetakerIndexRoute = AlysonNotetakerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AlysonNotetakerRouteRoute,
} as any)
const WorkspaceActivityUserEmailRoute =
  WorkspaceActivityUserEmailRouteImport.update({
    id: '/$userEmail',
    path: '/$userEmail',
    getParentRoute: () => WorkspaceActivityRoute,
  } as any)
const WebhooksRecallRoute = WebhooksRecallRouteImport.update({
  id: '/webhooks/recall',
  path: '/webhooks/recall',
  getParentRoute: () => rootRouteImport,
} as any)
const TimeDashboardPacingRoute = TimeDashboardPacingRouteImport.update({
  id: '/pacing',
  path: '/pacing',
  getParentRoute: () => TimeDashboardRoute,
} as any)
const TimeDashboardMonthlyPacingRoute =
  TimeDashboardMonthlyPacingRouteImport.update({
    id: '/monthly-pacing',
    path: '/monthly-pacing',
    getParentRoute: () => TimeDashboardRoute,
  } as any)
const TimeDashboardUserIdRoute = TimeDashboardUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => TimeDashboardRoute,
} as any)
const LeaveCalendarRoute = LeaveCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => LeaveRouteRoute,
} as any)
const LeaveAuditRoute = LeaveAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => LeaveRouteRoute,
} as any)
const LeaveAnalyticsRoute = LeaveAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => LeaveRouteRoute,
} as any)
const EmployeeScoringUserEmailRoute =
  EmployeeScoringUserEmailRouteImport.update({
    id: '/$userEmail',
    path: '/$userEmail',
    getParentRoute: () => EmployeeScoringRoute,
  } as any)
const BonusSimulateRoute = BonusSimulateRouteImport.update({
  id: '/simulate',
  path: '/simulate',
  getParentRoute: () => BonusRouteRoute,
} as any)
const BonusPlansRoute = BonusPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => BonusRouteRoute,
} as any)
const BonusAuditRoute = BonusAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => BonusRouteRoute,
} as any)
const BonusApprovalsRoute = BonusApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => BonusRouteRoute,
} as any)
const BonusAnalyticsRoute = BonusAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => BonusRouteRoute,
} as any)
const AlysonNotetakerUnifiedMeetingsRoute =
  AlysonNotetakerUnifiedMeetingsRouteImport.update({
    id: '/unified-meetings',
    path: '/unified-meetings',
    getParentRoute: () => AlysonNotetakerRouteRoute,
  } as any)
const AlysonNotetakerTasksRoute = AlysonNotetakerTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AlysonNotetakerRouteRoute,
} as any)
const AlysonNotetakerMeetingListRoute =
  AlysonNotetakerMeetingListRouteImport.update({
    id: '/meeting-list',
    path: '/meeting-list',
    getParentRoute: () => AlysonNotetakerRouteRoute,
  } as any)
const AlysonNotetakerCostTrackingRoute =
  AlysonNotetakerCostTrackingRouteImport.update({
    id: '/cost-tracking',
    path: '/cost-tracking',
    getParentRoute: () => AlysonNotetakerRouteRoute,
  } as any)
const AlysonNotetakerCalendarRoute = AlysonNotetakerCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AlysonNotetakerRouteRoute,
} as any)
const AlysonNotetakerBotJoinReportRoute =
  AlysonNotetakerBotJoinReportRouteImport.update({
    id: '/bot-join-report',
    path: '/bot-join-report',
    getParentRoute: () => AlysonNotetakerRouteRoute,
  } as any)
const AlysonNotetakerAnalyticsRoute =
  AlysonNotetakerAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AlysonNotetakerRouteRoute,
  } as any)
const ApiCronTimeDoctorTokenRoute = ApiCronTimeDoctorTokenRouteImport.update({
  id: '/api/cron/time-doctor-token',
  path: '/api/cron/time-doctor-token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronScheduledBotActivationRoute =
  ApiCronScheduledBotActivationRouteImport.update({
    id: '/api/cron/scheduled-bot-activation',
    path: '/api/cron/scheduled-bot-activation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCronRecallCalendarSyncRoute =
  ApiCronRecallCalendarSyncRouteImport.update({
    id: '/api/cron/recall-calendar-sync',
    path: '/api/cron/recall-calendar-sync',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCronNotetakerTranscriptsRoute =
  ApiCronNotetakerTranscriptsRouteImport.update({
    id: '/api/cron/notetaker-transcripts',
    path: '/api/cron/notetaker-transcripts',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCronDailyReportsRoute = ApiCronDailyReportsRouteImport.update({
  id: '/api/cron/daily-reports',
  path: '/api/cron/daily-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyticsWorkspaceActivityRoute =
  ApiAnalyticsWorkspaceActivityRouteImport.update({
    id: '/api/analytics/workspace-activity',
    path: '/api/analytics/workspace-activity',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAnalyticsUnifiedMeetingsRoute =
  ApiAnalyticsUnifiedMeetingsRouteImport.update({
    id: '/api/analytics/unified-meetings',
    path: '/api/analytics/unified-meetings',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAnalyticsEmployeeScoringRoute =
  ApiAnalyticsEmployeeScoringRouteImport.update({
    id: '/api/analytics/employee-scoring',
    path: '/api/analytics/employee-scoring',
    getParentRoute: () => rootRouteImport,
  } as any)
const AlysonNotetakerAnalyticsUnifiedMeetingsRoute =
  AlysonNotetakerAnalyticsUnifiedMeetingsRouteImport.update({
    id: '/unified-meetings',
    path: '/unified-meetings',
    getParentRoute: () => AlysonNotetakerAnalyticsRoute,
  } as any)
const ApiRecallWebhooksCalendarRoute =
  ApiRecallWebhooksCalendarRouteImport.update({
    id: '/api/recall/webhooks/calendar',
    path: '/api/recall/webhooks/calendar',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiRecallCalendarStatusRoute = ApiRecallCalendarStatusRouteImport.update({
  id: '/api/recall/calendar/status',
  path: '/api/recall/calendar/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRecallCalendarConnectRoute =
  ApiRecallCalendarConnectRouteImport.update({
    id: '/api/recall/calendar/connect',
    path: '/api/recall/calendar/connect',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiRecallCalendarCallbackRoute =
  ApiRecallCalendarCallbackRouteImport.update({
    id: '/api/recall/calendar/callback',
    path: '/api/recall/calendar/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAnalyticsWorkspaceActivityUserEmailRoute =
  ApiAnalyticsWorkspaceActivityUserEmailRouteImport.update({
    id: '/$userEmail',
    path: '/$userEmail',
    getParentRoute: () => ApiAnalyticsWorkspaceActivityRoute,
  } as any)
const ApiAnalyticsUnifiedMeetingsScheduleBotsRoute =
  ApiAnalyticsUnifiedMeetingsScheduleBotsRouteImport.update({
    id: '/schedule-bots',
    path: '/schedule-bots',
    getParentRoute: () => ApiAnalyticsUnifiedMeetingsRoute,
  } as any)
const ApiAnalyticsUnifiedMeetingsRefreshRoute =
  ApiAnalyticsUnifiedMeetingsRefreshRouteImport.update({
    id: '/refresh',
    path: '/refresh',
    getParentRoute: () => ApiAnalyticsUnifiedMeetingsRoute,
  } as any)
const ApiAnalyticsEmployeeScoringUserEmailRoute =
  ApiAnalyticsEmployeeScoringUserEmailRouteImport.update({
    id: '/$userEmail',
    path: '/$userEmail',
    getParentRoute: () => ApiAnalyticsEmployeeScoringRoute,
  } as any)
const ApiAnalyticsUnifiedMeetingsMeetingIdUnscheduleRoute =
  ApiAnalyticsUnifiedMeetingsMeetingIdUnscheduleRouteImport.update({
    id: '/$meetingId/unschedule',
    path: '/$meetingId/unschedule',
    getParentRoute: () => ApiAnalyticsUnifiedMeetingsRoute,
  } as any)
const ApiAnalyticsUnifiedMeetingsMeetingIdScheduleRoute =
  ApiAnalyticsUnifiedMeetingsMeetingIdScheduleRouteImport.update({
    id: '/$meetingId/schedule',
    path: '/$meetingId/schedule',
    getParentRoute: () => ApiAnalyticsUnifiedMeetingsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alyson-notetaker': typeof AlysonNotetakerRouteRouteWithChildren
  '/bonus': typeof BonusRouteRouteWithChildren
  '/leave': typeof LeaveRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/alyson-brain': typeof AlysonBrainRoute
  '/app': typeof AppRoute
  '/attendance': typeof AttendanceRoute
  '/auth': typeof AuthRoute
  '/boarding': typeof BoardingRoute
  '/documents': typeof DocumentsRoute
  '/employee-onboarding': typeof EmployeeOnboardingRoute
  '/employee-scoring': typeof EmployeeScoringRouteWithChildren
  '/equity': typeof EquityRoute
  '/handover-documentation': typeof HandoverDocumentationRoute
  '/help': typeof HelpRoute
  '/payroll': typeof PayrollRoute
  '/performance': typeof PerformanceRoute
  '/reports': typeof ReportsRoute
  '/team': typeof TeamRoute
  '/time-dashboard': typeof TimeDashboardRouteWithChildren
  '/workflows': typeof WorkflowsRoute
  '/workspace-activity': typeof WorkspaceActivityRouteWithChildren
  '/alyson-notetaker/analytics': typeof AlysonNotetakerAnalyticsRouteWithChildren
  '/alyson-notetaker/bot-join-report': typeof AlysonNotetakerBotJoinReportRoute
  '/alyson-notetaker/calendar': typeof AlysonNotetakerCalendarRoute
  '/alyson-notetaker/cost-tracking': typeof AlysonNotetakerCostTrackingRoute
  '/alyson-notetaker/meeting-list': typeof AlysonNotetakerMeetingListRoute
  '/alyson-notetaker/tasks': typeof AlysonNotetakerTasksRoute
  '/alyson-notetaker/unified-meetings': typeof AlysonNotetakerUnifiedMeetingsRoute
  '/bonus/analytics': typeof BonusAnalyticsRoute
  '/bonus/approvals': typeof BonusApprovalsRoute
  '/bonus/audit': typeof BonusAuditRoute
  '/bonus/plans': typeof BonusPlansRoute
  '/bonus/simulate': typeof BonusSimulateRoute
  '/employee-scoring/$userEmail': typeof EmployeeScoringUserEmailRoute
  '/leave/analytics': typeof LeaveAnalyticsRoute
  '/leave/audit': typeof LeaveAuditRoute
  '/leave/calendar': typeof LeaveCalendarRoute
  '/time-dashboard/$userId': typeof TimeDashboardUserIdRoute
  '/time-dashboard/monthly-pacing': typeof TimeDashboardMonthlyPacingRoute
  '/time-dashboard/pacing': typeof TimeDashboardPacingRoute
  '/webhooks/recall': typeof WebhooksRecallRoute
  '/workspace-activity/$userEmail': typeof WorkspaceActivityUserEmailRoute
  '/alyson-notetaker/': typeof AlysonNotetakerIndexRoute
  '/bonus/': typeof BonusIndexRoute
  '/leave/': typeof LeaveIndexRoute
  '/alyson-notetaker/analytics/unified-meetings': typeof AlysonNotetakerAnalyticsUnifiedMeetingsRoute
  '/api/analytics/employee-scoring': typeof ApiAnalyticsEmployeeScoringRouteWithChildren
  '/api/analytics/unified-meetings': typeof ApiAnalyticsUnifiedMeetingsRouteWithChildren
  '/api/analytics/workspace-activity': typeof ApiAnalyticsWorkspaceActivityRouteWithChildren
  '/api/cron/daily-reports': typeof ApiCronDailyReportsRoute
  '/api/cron/notetaker-transcripts': typeof ApiCronNotetakerTranscriptsRoute
  '/api/cron/recall-calendar-sync': typeof ApiCronRecallCalendarSyncRoute
  '/api/cron/scheduled-bot-activation': typeof ApiCronScheduledBotActivationRoute
  '/api/cron/time-doctor-token': typeof ApiCronTimeDoctorTokenRoute
  '/api/analytics/employee-scoring/$userEmail': typeof ApiAnalyticsEmployeeScoringUserEmailRoute
  '/api/analytics/unified-meetings/refresh': typeof ApiAnalyticsUnifiedMeetingsRefreshRoute
  '/api/analytics/unified-meetings/schedule-bots': typeof ApiAnalyticsUnifiedMeetingsScheduleBotsRoute
  '/api/analytics/workspace-activity/$userEmail': typeof ApiAnalyticsWorkspaceActivityUserEmailRoute
  '/api/recall/calendar/callback': typeof ApiRecallCalendarCallbackRoute
  '/api/recall/calendar/connect': typeof ApiRecallCalendarConnectRoute
  '/api/recall/calendar/status': typeof ApiRecallCalendarStatusRoute
  '/api/recall/webhooks/calendar': typeof ApiRecallWebhooksCalendarRoute
  '/api/analytics/unified-meetings/$meetingId/schedule': typeof ApiAnalyticsUnifiedMeetingsMeetingIdScheduleRoute
  '/api/analytics/unified-meetings/$meetingId/unschedule': typeof ApiAnalyticsUnifiedMeetingsMeetingIdUnscheduleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/alyson-brain': typeof AlysonBrainRoute
  '/app': typeof AppRoute
  '/attendance': typeof AttendanceRoute
  '/auth': typeof AuthRoute
  '/boarding': typeof BoardingRoute
  '/documents': typeof DocumentsRoute
  '/employee-onboarding': typeof EmployeeOnboardingRoute
  '/employee-scoring': typeof EmployeeScoringRouteWithChildren
  '/equity': typeof EquityRoute
  '/handover-documentation': typeof HandoverDocumentationRoute
  '/help': typeof HelpRoute
  '/payroll': typeof PayrollRoute
  '/performance': typeof PerformanceRoute
  '/reports': typeof ReportsRoute
  '/team': typeof TeamRoute
  '/time-dashboard': typeof TimeDashboardRouteWithChildren
  '/workflows': typeof WorkflowsRoute
  '/workspace-activity': typeof WorkspaceActivityRouteWithChildren
  '/alyson-notetaker/analytics': typeof AlysonNotetakerAnalyticsRouteWithChildren
  '/alyson-notetaker/bot-join-report': typeof AlysonNotetakerBotJoinReportRoute
  '/alyson-notetaker/calendar': typeof AlysonNotetakerCalendarRoute
  '/alyson-notetaker/cost-tracking': typeof AlysonNotetakerCostTrackingRoute
  '/alyson-notetaker/meeting-list': typeof AlysonNotetakerMeetingListRoute
  '/alyson-notetaker/tasks': typeof AlysonNotetakerTasksRoute
  '/alyson-notetaker/unified-meetings': typeof AlysonNotetakerUnifiedMeetingsRoute
  '/bonus/analytics': typeof BonusAnalyticsRoute
  '/bonus/approvals': typeof BonusApprovalsRoute
  '/bonus/audit': typeof BonusAuditRoute
  '/bonus/plans': typeof BonusPlansRoute
  '/bonus/simulate': typeof BonusSimulateRoute
  '/employee-scoring/$userEmail': typeof EmployeeScoringUserEmailRoute
  '/leave/analytics': typeof LeaveAnalyticsRoute
  '/leave/audit': typeof LeaveAuditRoute
  '/leave/calendar': typeof LeaveCalendarRoute
  '/time-dashboard/$userId': typeof TimeDashboardUserIdRoute
  '/time-dashboard/monthly-pacing': typeof TimeDashboardMonthlyPacingRoute
  '/time-dashboard/pacing': typeof TimeDashboardPacingRoute
  '/webhooks/recall': typeof WebhooksRecallRoute
  '/workspace-activity/$userEmail': typeof WorkspaceActivityUserEmailRoute
  '/alyson-notetaker': typeof AlysonNotetakerIndexRoute
  '/bonus': typeof BonusIndexRoute
  '/leave': typeof LeaveIndexRoute
  '/alyson-notetaker/analytics/unified-meetings': typeof AlysonNotetakerAnalyticsUnifiedMeetingsRoute
  '/api/analytics/employee-scoring': typeof ApiAnalyticsEmployeeScoringRouteWithChildren
  '/api/analytics/unified-meetings': typeof ApiAnalyticsUnifiedMeetingsRouteWithChildren
  '/api/analytics/workspace-activity': typeof ApiAnalyticsWorkspaceActivityRouteWithChildren
  '/api/cron/daily-reports': typeof ApiCronDailyReportsRoute
  '/api/cron/notetaker-transcripts': typeof ApiCronNotetakerTranscriptsRoute
  '/api/cron/recall-calendar-sync': typeof ApiCronRecallCalendarSyncRoute
  '/api/cron/scheduled-bot-activation': typeof ApiCronScheduledBotActivationRoute
  '/api/cron/time-doctor-token': typeof ApiCronTimeDoctorTokenRoute
  '/api/analytics/employee-scoring/$userEmail': typeof ApiAnalyticsEmployeeScoringUserEmailRoute
  '/api/analytics/unified-meetings/refresh': typeof ApiAnalyticsUnifiedMeetingsRefreshRoute
  '/api/analytics/unified-meetings/schedule-bots': typeof ApiAnalyticsUnifiedMeetingsScheduleBotsRoute
  '/api/analytics/workspace-activity/$userEmail': typeof ApiAnalyticsWorkspaceActivityUserEmailRoute
  '/api/recall/calendar/callback': typeof ApiRecallCalendarCallbackRoute
  '/api/recall/calendar/connect': typeof ApiRecallCalendarConnectRoute
  '/api/recall/calendar/status': typeof ApiRecallCalendarStatusRoute
  '/api/recall/webhooks/calendar': typeof ApiRecallWebhooksCalendarRoute
  '/api/analytics/unified-meetings/$meetingId/schedule': typeof ApiAnalyticsUnifiedMeetingsMeetingIdScheduleRoute
  '/api/analytics/unified-meetings/$meetingId/unschedule': typeof ApiAnalyticsUnifiedMeetingsMeetingIdUnscheduleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alyson-notetaker': typeof AlysonNotetakerRouteRouteWithChildren
  '/bonus': typeof BonusRouteRouteWithChildren
  '/leave': typeof LeaveRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/alyson-brain': typeof AlysonBrainRoute
  '/app': typeof AppRoute
  '/attendance': typeof AttendanceRoute
  '/auth': typeof AuthRoute
  '/boarding': typeof BoardingRoute
  '/documents': typeof DocumentsRoute
  '/employee-onboarding': typeof EmployeeOnboardingRoute
  '/employee-scoring': typeof EmployeeScoringRouteWithChildren
  '/equity': typeof EquityRoute
  '/handover-documentation': typeof HandoverDocumentationRoute
  '/help': typeof HelpRoute
  '/payroll': typeof PayrollRoute
  '/performance': typeof PerformanceRoute
  '/reports': typeof ReportsRoute
  '/team': typeof TeamRoute
  '/time-dashboard': typeof TimeDashboardRouteWithChildren
  '/workflows': typeof WorkflowsRoute
  '/workspace-activity': typeof WorkspaceActivityRouteWithChildren
  '/alyson-notetaker/analytics': typeof AlysonNotetakerAnalyticsRouteWithChildren
  '/alyson-notetaker/bot-join-report': typeof AlysonNotetakerBotJoinReportRoute
  '/alyson-notetaker/calendar': typeof AlysonNotetakerCalendarRoute
  '/alyson-notetaker/cost-tracking': typeof AlysonNotetakerCostTrackingRoute
  '/alyson-notetaker/meeting-list': typeof AlysonNotetakerMeetingListRoute
  '/alyson-notetaker/tasks': typeof AlysonNotetakerTasksRoute
  '/alyson-notetaker/unified-meetings': typeof AlysonNotetakerUnifiedMeetingsRoute
  '/bonus/analytics': typeof BonusAnalyticsRoute
  '/bonus/approvals': typeof BonusApprovalsRoute
  '/bonus/audit': typeof BonusAuditRoute
  '/bonus/plans': typeof BonusPlansRoute
  '/bonus/simulate': typeof BonusSimulateRoute
  '/employee-scoring/$userEmail': typeof EmployeeScoringUserEmailRoute
  '/leave/analytics': typeof LeaveAnalyticsRoute
  '/leave/audit': typeof LeaveAuditRoute
  '/leave/calendar': typeof LeaveCalendarRoute
  '/time-dashboard/$userId': typeof TimeDashboardUserIdRoute
  '/time-dashboard/monthly-pacing': typeof TimeDashboardMonthlyPacingRoute
  '/time-dashboard/pacing': typeof TimeDashboardPacingRoute
  '/webhooks/recall': typeof WebhooksRecallRoute
  '/workspace-activity/$userEmail': typeof WorkspaceActivityUserEmailRoute
  '/alyson-notetaker/': typeof AlysonNotetakerIndexRoute
  '/bonus/': typeof BonusIndexRoute
  '/leave/': typeof LeaveIndexRoute
  '/alyson-notetaker/analytics/unified-meetings': typeof AlysonNotetakerAnalyticsUnifiedMeetingsRoute
  '/api/analytics/employee-scoring': typeof ApiAnalyticsEmployeeScoringRouteWithChildren
  '/api/analytics/unified-meetings': typeof ApiAnalyticsUnifiedMeetingsRouteWithChildren
  '/api/analytics/workspace-activity': typeof ApiAnalyticsWorkspaceActivityRouteWithChildren
  '/api/cron/daily-reports': typeof ApiCronDailyReportsRoute
  '/api/cron/notetaker-transcripts': typeof ApiCronNotetakerTranscriptsRoute
  '/api/cron/recall-calendar-sync': typeof ApiCronRecallCalendarSyncRoute
  '/api/cron/scheduled-bot-activation': typeof ApiCronScheduledBotActivationRoute
  '/api/cron/time-doctor-token': typeof ApiCronTimeDoctorTokenRoute
  '/api/analytics/employee-scoring/$userEmail': typeof ApiAnalyticsEmployeeScoringUserEmailRoute
  '/api/analytics/unified-meetings/refresh': typeof ApiAnalyticsUnifiedMeetingsRefreshRoute
  '/api/analytics/unified-meetings/schedule-bots': typeof ApiAnalyticsUnifiedMeetingsScheduleBotsRoute
  '/api/analytics/workspace-activity/$userEmail': typeof ApiAnalyticsWorkspaceActivityUserEmailRoute
  '/api/recall/calendar/callback': typeof ApiRecallCalendarCallbackRoute
  '/api/recall/calendar/connect': typeof ApiRecallCalendarConnectRoute
  '/api/recall/calendar/status': typeof ApiRecallCalendarStatusRoute
  '/api/recall/webhooks/calendar': typeof ApiRecallWebhooksCalendarRoute
  '/api/analytics/unified-meetings/$meetingId/schedule': typeof ApiAnalyticsUnifiedMeetingsMeetingIdScheduleRoute
  '/api/analytics/unified-meetings/$meetingId/unschedule': typeof ApiAnalyticsUnifiedMeetingsMeetingIdUnscheduleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alyson-notetaker'
    | '/bonus'
    | '/leave'
    | '/admin'
    | '/alyson-brain'
    | '/app'
    | '/attendance'
    | '/auth'
    | '/boarding'
    | '/documents'
    | '/employee-onboarding'
    | '/employee-scoring'
    | '/equity'
    | '/handover-documentation'
    | '/help'
    | '/payroll'
    | '/performance'
    | '/reports'
    | '/team'
    | '/time-dashboard'
    | '/workflows'
    | '/workspace-activity'
    | '/alyson-notetaker/analytics'
    | '/alyson-notetaker/bot-join-report'
    | '/alyson-notetaker/calendar'
    | '/alyson-notetaker/cost-tracking'
    | '/alyson-notetaker/meeting-list'
    | '/alyson-notetaker/tasks'
    | '/alyson-notetaker/unified-meetings'
    | '/bonus/analytics'
    | '/bonus/approvals'
    | '/bonus/audit'
    | '/bonus/plans'
    | '/bonus/simulate'
    | '/employee-scoring/$userEmail'
    | '/leave/analytics'
    | '/leave/audit'
    | '/leave/calendar'
    | '/time-dashboard/$userId'
    | '/time-dashboard/monthly-pacing'
    | '/time-dashboard/pacing'
    | '/webhooks/recall'
    | '/workspace-activity/$userEmail'
    | '/alyson-notetaker/'
    | '/bonus/'
    | '/leave/'
    | '/alyson-notetaker/analytics/unified-meetings'
    | '/api/analytics/employee-scoring'
    | '/api/analytics/unified-meetings'
    | '/api/analytics/workspace-activity'
    | '/api/cron/daily-reports'
    | '/api/cron/notetaker-transcripts'
    | '/api/cron/recall-calendar-sync'
    | '/api/cron/scheduled-bot-activation'
    | '/api/cron/time-doctor-token'
    | '/api/analytics/employee-scoring/$userEmail'
    | '/api/analytics/unified-meetings/refresh'
    | '/api/analytics/unified-meetings/schedule-bots'
    | '/api/analytics/workspace-activity/$userEmail'
    | '/api/recall/calendar/callback'
    | '/api/recall/calendar/connect'
    | '/api/recall/calendar/status'
    | '/api/recall/webhooks/calendar'
    | '/api/analytics/unified-meetings/$meetingId/schedule'
    | '/api/analytics/unified-meetings/$meetingId/unschedule'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/alyson-brain'
    | '/app'
    | '/attendance'
    | '/auth'
    | '/boarding'
    | '/documents'
    | '/employee-onboarding'
    | '/employee-scoring'
    | '/equity'
    | '/handover-documentation'
    | '/help'
    | '/payroll'
    | '/performance'
    | '/reports'
    | '/team'
    | '/time-dashboard'
    | '/workflows'
    | '/workspace-activity'
    | '/alyson-notetaker/analytics'
    | '/alyson-notetaker/bot-join-report'
    | '/alyson-notetaker/calendar'
    | '/alyson-notetaker/cost-tracking'
    | '/alyson-notetaker/meeting-list'
    | '/alyson-notetaker/tasks'
    | '/alyson-notetaker/unified-meetings'
    | '/bonus/analytics'
    | '/bonus/approvals'
    | '/bonus/audit'
    | '/bonus/plans'
    | '/bonus/simulate'
    | '/employee-scoring/$userEmail'
    | '/leave/analytics'
    | '/leave/audit'
    | '/leave/calendar'
    | '/time-dashboard/$userId'
    | '/time-dashboard/monthly-pacing'
    | '/time-dashboard/pacing'
    | '/webhooks/recall'
    | '/workspace-activity/$userEmail'
    | '/alyson-notetaker'
    | '/bonus'
    | '/leave'
    | '/alyson-notetaker/analytics/unified-meetings'
    | '/api/analytics/employee-scoring'
    | '/api/analytics/unified-meetings'
    | '/api/analytics/workspace-activity'
    | '/api/cron/daily-reports'
    | '/api/cron/notetaker-transcripts'
    | '/api/cron/recall-calendar-sync'
    | '/api/cron/scheduled-bot-activation'
    | '/api/cron/time-doctor-token'
    | '/api/analytics/employee-scoring/$userEmail'
    | '/api/analytics/unified-meetings/refresh'
    | '/api/analytics/unified-meetings/schedule-bots'
    | '/api/analytics/workspace-activity/$userEmail'
    | '/api/recall/calendar/callback'
    | '/api/recall/calendar/connect'
    | '/api/recall/calendar/status'
    | '/api/recall/webhooks/calendar'
    | '/api/analytics/unified-meetings/$meetingId/schedule'
    | '/api/analytics/unified-meetings/$meetingId/unschedule'
  id:
    | '__root__'
    | '/'
    | '/alyson-notetaker'
    | '/bonus'
    | '/leave'
    | '/admin'
    | '/alyson-brain'
    | '/app'
    | '/attendance'
    | '/auth'
    | '/boarding'
    | '/documents'
    | '/employee-onboarding'
    | '/employee-scoring'
    | '/equity'
    | '/handover-documentation'
    | '/help'
    | '/payroll'
    | '/performance'
    | '/reports'
    | '/team'
    | '/time-dashboard'
    | '/workflows'
    | '/workspace-activity'
    | '/alyson-notetaker/analytics'
    | '/alyson-notetaker/bot-join-report'
    | '/alyson-notetaker/calendar'
    | '/alyson-notetaker/cost-tracking'
    | '/alyson-notetaker/meeting-list'
    | '/alyson-notetaker/tasks'
    | '/alyson-notetaker/unified-meetings'
    | '/bonus/analytics'
    | '/bonus/approvals'
    | '/bonus/audit'
    | '/bonus/plans'
    | '/bonus/simulate'
    | '/employee-scoring/$userEmail'
    | '/leave/analytics'
    | '/leave/audit'
    | '/leave/calendar'
    | '/time-dashboard/$userId'
    | '/time-dashboard/monthly-pacing'
    | '/time-dashboard/pacing'
    | '/webhooks/recall'
    | '/workspace-activity/$userEmail'
    | '/alyson-notetaker/'
    | '/bonus/'
    | '/leave/'
    | '/alyson-notetaker/analytics/unified-meetings'
    | '/api/analytics/employee-scoring'
    | '/api/analytics/unified-meetings'
    | '/api/analytics/workspace-activity'
    | '/api/cron/daily-reports'
    | '/api/cron/notetaker-transcripts'
    | '/api/cron/recall-calendar-sync'
    | '/api/cron/scheduled-bot-activation'
    | '/api/cron/time-doctor-token'
    | '/api/analytics/employee-scoring/$userEmail'
    | '/api/analytics/unified-meetings/refresh'
    | '/api/analytics/unified-meetings/schedule-bots'
    | '/api/analytics/workspace-activity/$userEmail'
    | '/api/recall/calendar/callback'
    | '/api/recall/calendar/connect'
    | '/api/recall/calendar/status'
    | '/api/recall/webhooks/calendar'
    | '/api/analytics/unified-meetings/$meetingId/schedule'
    | '/api/analytics/unified-meetings/$meetingId/unschedule'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlysonNotetakerRouteRoute: typeof AlysonNotetakerRouteRouteWithChildren
  BonusRouteRoute: typeof BonusRouteRouteWithChildren
  LeaveRouteRoute: typeof LeaveRouteRouteWithChildren
  AdminRoute: typeof AdminRoute
  AlysonBrainRoute: typeof AlysonBrainRoute
  AppRoute: typeof AppRoute
  AttendanceRoute: typeof AttendanceRoute
  AuthRoute: typeof AuthRoute
  BoardingRoute: typeof BoardingRoute
  DocumentsRoute: typeof DocumentsRoute
  EmployeeOnboardingRoute: typeof EmployeeOnboardingRoute
  EmployeeScoringRoute: typeof EmployeeScoringRouteWithChildren
  EquityRoute: typeof EquityRoute
  HandoverDocumentationRoute: typeof HandoverDocumentationRoute
  HelpRoute: typeof HelpRoute
  PayrollRoute: typeof PayrollRoute
  PerformanceRoute: typeof PerformanceRoute
  ReportsRoute: typeof ReportsRoute
  TeamRoute: typeof TeamRoute
  TimeDashboardRoute: typeof TimeDashboardRouteWithChildren
  WorkflowsRoute: typeof WorkflowsRoute
  WorkspaceActivityRoute: typeof WorkspaceActivityRouteWithChildren
  WebhooksRecallRoute: typeof WebhooksRecallRoute
  ApiAnalyticsEmployeeScoringRoute: typeof ApiAnalyticsEmployeeScoringRouteWithChildren
  ApiAnalyticsUnifiedMeetingsRoute: typeof ApiAnalyticsUnifiedMeetingsRouteWithChildren
  ApiAnalyticsWorkspaceActivityRoute: typeof ApiAnalyticsWorkspaceActivityRouteWithChildren
  ApiCronDailyReportsRoute: typeof ApiCronDailyReportsRoute
  ApiCronNotetakerTranscriptsRoute: typeof ApiCronNotetakerTranscriptsRoute
  ApiCronRecallCalendarSyncRoute: typeof ApiCronRecallCalendarSyncRoute
  ApiCronScheduledBotActivationRoute: typeof ApiCronScheduledBotActivationRoute
  ApiCronTimeDoctorTokenRoute: typeof ApiCronTimeDoctorTokenRoute
  ApiRecallCalendarCallbackRoute: typeof ApiRecallCalendarCallbackRoute
  ApiRecallCalendarConnectRoute: typeof ApiRecallCalendarConnectRoute
  ApiRecallCalendarStatusRoute: typeof ApiRecallCalendarStatusRoute
  ApiRecallWebhooksCalendarRoute: typeof ApiRecallWebhooksCalendarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace-activity': {
      id: '/workspace-activity'
      path: '/workspace-activity'
      fullPath: '/workspace-activity'
      preLoaderRoute: typeof WorkspaceActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows': {
      id: '/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/time-dashboard': {
      id: '/time-dashboard'
      path: '/time-dashboard'
      fullPath: '/time-dashboard'
      preLoaderRoute: typeof TimeDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance': {
      id: '/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof PerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payroll': {
      id: '/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof PayrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handover-documentation': {
      id: '/handover-documentation'
      path: '/handover-documentation'
      fullPath: '/handover-documentation'
      preLoaderRoute: typeof HandoverDocumentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equity': {
      id: '/equity'
      path: '/equity'
      fullPath: '/equity'
      preLoaderRoute: typeof EquityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee-scoring': {
      id: '/employee-scoring'
      path: '/employee-scoring'
      fullPath: '/employee-scoring'
      preLoaderRoute: typeof EmployeeScoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee-onboarding': {
      id: '/employee-onboarding'
      path: '/employee-onboarding'
      fullPath: '/employee-onboarding'
      preLoaderRoute: typeof EmployeeOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boarding': {
      id: '/boarding'
      path: '/boarding'
      fullPath: '/boarding'
      preLoaderRoute: typeof BoardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alyson-brain': {
      id: '/alyson-brain'
      path: '/alyson-brain'
      fullPath: '/alyson-brain'
      preLoaderRoute: typeof AlysonBrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leave': {
      id: '/leave'
      path: '/leave'
      fullPath: '/leave'
      preLoaderRoute: typeof LeaveRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bonus': {
      id: '/bonus'
      path: '/bonus'
      fullPath: '/bonus'
      preLoaderRoute: typeof BonusRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alyson-notetaker': {
      id: '/alyson-notetaker'
      path: '/alyson-notetaker'
      fullPath: '/alyson-notetaker'
      preLoaderRoute: typeof AlysonNotetakerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leave/': {
      id: '/leave/'
      path: '/'
      fullPath: '/leave/'
      preLoaderRoute: typeof LeaveIndexRouteImport
      parentRoute: typeof LeaveRouteRoute
    }
    '/bonus/': {
      id: '/bonus/'
      path: '/'
      fullPath: '/bonus/'
      preLoaderRoute: typeof BonusIndexRouteImport
      parentRoute: typeof BonusRouteRoute
    }
    '/alyson-notetaker/': {
      id: '/alyson-notetaker/'
      path: '/'
      fullPath: '/alyson-notetaker/'
      preLoaderRoute: typeof AlysonNotetakerIndexRouteImport
      parentRoute: typeof AlysonNotetakerRouteRoute
    }
    '/workspace-activity/$userEmail': {
      id: '/workspace-activity/$userEmail'
      path: '/$userEmail'
      fullPath: '/workspace-activity/$userEmail'
      preLoaderRoute: typeof WorkspaceActivityUserEmailRouteImport
      parentRoute: typeof WorkspaceActivityRoute
    }
    '/webhooks/recall': {
      id: '/webhooks/recall'
      path: '/webhooks/recall'
      fullPath: '/webhooks/recall'
      preLoaderRoute: typeof WebhooksRecallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/time-dashboard/pacing': {
      id: '/time-dashboard/pacing'
      path: '/pacing'
      fullPath: '/time-dashboard/pacing'
      preLoaderRoute: typeof TimeDashboardPacingRouteImport
      parentRoute: typeof TimeDashboardRoute
    }
    '/time-dashboard/monthly-pacing': {
      id: '/time-dashboard/monthly-pacing'
      path: '/monthly-pacing'
      fullPath: '/time-dashboard/monthly-pacing'
      preLoaderRoute: typeof TimeDashboardMonthlyPacingRouteImport
      parentRoute: typeof TimeDashboardRoute
    }
    '/time-dashboard/$userId': {
      id: '/time-dashboard/$userId'
      path: '/$userId'
      fullPath: '/time-dashboard/$userId'
      preLoaderRoute: typeof TimeDashboardUserIdRouteImport
      parentRoute: typeof TimeDashboardRoute
    }
    '/leave/calendar': {
      id: '/leave/calendar'
      path: '/calendar'
      fullPath: '/leave/calendar'
      preLoaderRoute: typeof LeaveCalendarRouteImport
      parentRoute: typeof LeaveRouteRoute
    }
    '/leave/audit': {
      id: '/leave/audit'
      path: '/audit'
      fullPath: '/leave/audit'
      preLoaderRoute: typeof LeaveAuditRouteImport
      parentRoute: typeof LeaveRouteRoute
    }
    '/leave/analytics': {
      id: '/leave/analytics'
      path: '/analytics'
      fullPath: '/leave/analytics'
      preLoaderRoute: typeof LeaveAnalyticsRouteImport
      parentRoute: typeof LeaveRouteRoute
    }
    '/employee-scoring/$userEmail': {
      id: '/employee-scoring/$userEmail'
      path: '/$userEmail'
      fullPath: '/employee-scoring/$userEmail'
      preLoaderRoute: typeof EmployeeScoringUserEmailRouteImport
      parentRoute: typeof EmployeeScoringRoute
    }
    '/bonus/simulate': {
      id: '/bonus/simulate'
      path: '/simulate'
      fullPath: '/bonus/simulate'
      preLoaderRoute: typeof BonusSimulateRouteImport
      parentRoute: typeof BonusRouteRoute
    }
    '/bonus/plans': {
      id: '/bonus/plans'
      path: '/plans'
      fullPath: '/bonus/plans'
      preLoaderRoute: typeof BonusPlansRouteImport
      parentRoute: typeof BonusRouteRoute
    }
    '/bonus/audit': {
      id: '/bonus/audit'
      path: '/audit'
      fullPath: '/bonus/audit'
      preLoaderRoute: typeof BonusAuditRouteImport
      parentRoute: typeof BonusRouteRoute
    }
    '/bonus/approvals': {
      id: '/bonus/approvals'
      path: '/approvals'
      fullPath: '/bonus/approvals'
      preLoaderRoute: typeof BonusApprovalsRouteImport
      parentRoute: typeof BonusRouteRoute
    }
    '/bonus/analytics': {
      id: '/bonus/analytics'
      path: '/analytics'
      fullPath: '/bonus/analytics'
      preLoaderRoute: typeof BonusAnalyticsRouteImport
      parentRoute: typeof BonusRouteRoute
    }
    '/alyson-notetaker/unified-meetings': {
      id: '/alyson-notetaker/unified-meetings'
      path: '/unified-meetings'
      fullPath: '/alyson-notetaker/unified-meetings'
      preLoaderRoute: typeof AlysonNotetakerUnifiedMeetingsRouteImport
      parentRoute: typeof AlysonNotetakerRouteRoute
    }
    '/alyson-notetaker/tasks': {
      id: '/alyson-notetaker/tasks'
      path: '/tasks'
      fullPath: '/alyson-notetaker/tasks'
      preLoaderRoute: typeof AlysonNotetakerTasksRouteImport
      parentRoute: typeof AlysonNotetakerRouteRoute
    }
    '/alyson-notetaker/meeting-list': {
      id: '/alyson-notetaker/meeting-list'
      path: '/meeting-list'
      fullPath: '/alyson-notetaker/meeting-list'
      preLoaderRoute: typeof AlysonNotetakerMeetingListRouteImport
      parentRoute: typeof AlysonNotetakerRouteRoute
    }
    '/alyson-notetaker/cost-tracking': {
      id: '/alyson-notetaker/cost-tracking'
      path: '/cost-tracking'
      fullPath: '/alyson-notetaker/cost-tracking'
      preLoaderRoute: typeof AlysonNotetakerCostTrackingRouteImport
      parentRoute: typeof AlysonNotetakerRouteRoute
    }
    '/alyson-notetaker/calendar': {
      id: '/alyson-notetaker/calendar'
      path: '/calendar'
      fullPath: '/alyson-notetaker/calendar'
      preLoaderRoute: typeof AlysonNotetakerCalendarRouteImport
      parentRoute: typeof AlysonNotetakerRouteRoute
    }
    '/alyson-notetaker/bot-join-report': {
      id: '/alyson-notetaker/bot-join-report'
      path: '/bot-join-report'
      fullPath: '/alyson-notetaker/bot-join-report'
      preLoaderRoute: typeof AlysonNotetakerBotJoinReportRouteImport
      parentRoute: typeof AlysonNotetakerRouteRoute
    }
    '/alyson-notetaker/analytics': {
      id: '/alyson-notetaker/analytics'
      path: '/analytics'
      fullPath: '/alyson-notetaker/analytics'
      preLoaderRoute: typeof AlysonNotetakerAnalyticsRouteImport
      parentRoute: typeof AlysonNotetakerRouteRoute
    }
    '/api/cron/time-doctor-token': {
      id: '/api/cron/time-doctor-token'
      path: '/api/cron/time-doctor-token'
      fullPath: '/api/cron/time-doctor-token'
      preLoaderRoute: typeof ApiCronTimeDoctorTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/scheduled-bot-activation': {
      id: '/api/cron/scheduled-bot-activation'
      path: '/api/cron/scheduled-bot-activation'
      fullPath: '/api/cron/scheduled-bot-activation'
      preLoaderRoute: typeof ApiCronScheduledBotActivationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/recall-calendar-sync': {
      id: '/api/cron/recall-calendar-sync'
      path: '/api/cron/recall-calendar-sync'
      fullPath: '/api/cron/recall-calendar-sync'
      preLoaderRoute: typeof ApiCronRecallCalendarSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/notetaker-transcripts': {
      id: '/api/cron/notetaker-transcripts'
      path: '/api/cron/notetaker-transcripts'
      fullPath: '/api/cron/notetaker-transcripts'
      preLoaderRoute: typeof ApiCronNotetakerTranscriptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/daily-reports': {
      id: '/api/cron/daily-reports'
      path: '/api/cron/daily-reports'
      fullPath: '/api/cron/daily-reports'
      preLoaderRoute: typeof ApiCronDailyReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analytics/workspace-activity': {
      id: '/api/analytics/workspace-activity'
      path: '/api/analytics/workspace-activity'
      fullPath: '/api/analytics/workspace-activity'
      preLoaderRoute: typeof ApiAnalyticsWorkspaceActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analytics/unified-meetings': {
      id: '/api/analytics/unified-meetings'
      path: '/api/analytics/unified-meetings'
      fullPath: '/api/analytics/unified-meetings'
      preLoaderRoute: typeof ApiAnalyticsUnifiedMeetingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analytics/employee-scoring': {
      id: '/api/analytics/employee-scoring'
      path: '/api/analytics/employee-scoring'
      fullPath: '/api/analytics/employee-scoring'
      preLoaderRoute: typeof ApiAnalyticsEmployeeScoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alyson-notetaker/analytics/unified-meetings': {
      id: '/alyson-notetaker/analytics/unified-meetings'
      path: '/unified-meetings'
      fullPath: '/alyson-notetaker/analytics/unified-meetings'
      preLoaderRoute: typeof AlysonNotetakerAnalyticsUnifiedMeetingsRouteImport
      parentRoute: typeof AlysonNotetakerAnalyticsRoute
    }
    '/api/recall/webhooks/calendar': {
      id: '/api/recall/webhooks/calendar'
      path: '/api/recall/webhooks/calendar'
      fullPath: '/api/recall/webhooks/calendar'
      preLoaderRoute: typeof ApiRecallWebhooksCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/recall/calendar/status': {
      id: '/api/recall/calendar/status'
      path: '/api/recall/calendar/status'
      fullPath: '/api/recall/calendar/status'
      preLoaderRoute: typeof ApiRecallCalendarStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/recall/calendar/connect': {
      id: '/api/recall/calendar/connect'
      path: '/api/recall/calendar/connect'
      fullPath: '/api/recall/calendar/connect'
      preLoaderRoute: typeof ApiRecallCalendarConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/recall/calendar/callback': {
      id: '/api/recall/calendar/callback'
      path: '/api/recall/calendar/callback'
      fullPath: '/api/recall/calendar/callback'
      preLoaderRoute: typeof ApiRecallCalendarCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analytics/workspace-activity/$userEmail': {
      id: '/api/analytics/workspace-activity/$userEmail'
      path: '/$userEmail'
      fullPath: '/api/analytics/workspace-activity/$userEmail'
      preLoaderRoute: typeof ApiAnalyticsWorkspaceActivityUserEmailRouteImport
      parentRoute: typeof ApiAnalyticsWorkspaceActivityRoute
    }
    '/api/analytics/unified-meetings/schedule-bots': {
      id: '/api/analytics/unified-meetings/schedule-bots'
      path: '/schedule-bots'
      fullPath: '/api/analytics/unified-meetings/schedule-bots'
      preLoaderRoute: typeof ApiAnalyticsUnifiedMeetingsScheduleBotsRouteImport
      parentRoute: typeof ApiAnalyticsUnifiedMeetingsRoute
    }
    '/api/analytics/unified-meetings/refresh': {
      id: '/api/analytics/unified-meetings/refresh'
      path: '/refresh'
      fullPath: '/api/analytics/unified-meetings/refresh'
      preLoaderRoute: typeof ApiAnalyticsUnifiedMeetingsRefreshRouteImport
      parentRoute: typeof ApiAnalyticsUnifiedMeetingsRoute
    }
    '/api/analytics/employee-scoring/$userEmail': {
      id: '/api/analytics/employee-scoring/$userEmail'
      path: '/$userEmail'
      fullPath: '/api/analytics/employee-scoring/$userEmail'
      preLoaderRoute: typeof ApiAnalyticsEmployeeScoringUserEmailRouteImport
      parentRoute: typeof ApiAnalyticsEmployeeScoringRoute
    }
    '/api/analytics/unified-meetings/$meetingId/unschedule': {
      id: '/api/analytics/unified-meetings/$meetingId/unschedule'
      path: '/$meetingId/unschedule'
      fullPath: '/api/analytics/unified-meetings/$meetingId/unschedule'
      preLoaderRoute: typeof ApiAnalyticsUnifiedMeetingsMeetingIdUnscheduleRouteImport
      parentRoute: typeof ApiAnalyticsUnifiedMeetingsRoute
    }
    '/api/analytics/unified-meetings/$meetingId/schedule': {
      id: '/api/analytics/unified-meetings/$meetingId/schedule'
      path: '/$meetingId/schedule'
      fullPath: '/api/analytics/unified-meetings/$meetingId/schedule'
      preLoaderRoute: typeof ApiAnalyticsUnifiedMeetingsMeetingIdScheduleRouteImport
      parentRoute: typeof ApiAnalyticsUnifiedMeetingsRoute
    }
  }
}

interface AlysonNotetakerAnalyticsRouteChildren {
  AlysonNotetakerAnalyticsUnifiedMeetingsRoute: typeof AlysonNotetakerAnalyticsUnifiedMeetingsRoute
}

const AlysonNotetakerAnalyticsRouteChildren: AlysonNotetakerAnalyticsRouteChildren =
  {
    AlysonNotetakerAnalyticsUnifiedMeetingsRoute:
      AlysonNotetakerAnalyticsUnifiedMeetingsRoute,
  }

const AlysonNotetakerAnalyticsRouteWithChildren =
  AlysonNotetakerAnalyticsRoute._addFileChildren(
    AlysonNotetakerAnalyticsRouteChildren,
  )

interface AlysonNotetakerRouteRouteChildren {
  AlysonNotetakerAnalyticsRoute: typeof AlysonNotetakerAnalyticsRouteWithChildren
  AlysonNotetakerBotJoinReportRoute: typeof AlysonNotetakerBotJoinReportRoute
  AlysonNotetakerCalendarRoute: typeof AlysonNotetakerCalendarRoute
  AlysonNotetakerCostTrackingRoute: typeof AlysonNotetakerCostTrackingRoute
  AlysonNotetakerMeetingListRoute: typeof AlysonNotetakerMeetingListRoute
  AlysonNotetakerTasksRoute: typeof AlysonNotetakerTasksRoute
  AlysonNotetakerUnifiedMeetingsRoute: typeof AlysonNotetakerUnifiedMeetingsRoute
  AlysonNotetakerIndexRoute: typeof AlysonNotetakerIndexRoute
}

const AlysonNotetakerRouteRouteChildren: AlysonNotetakerRouteRouteChildren = {
  AlysonNotetakerAnalyticsRoute: AlysonNotetakerAnalyticsRouteWithChildren,
  AlysonNotetakerBotJoinReportRoute: AlysonNotetakerBotJoinReportRoute,
  AlysonNotetakerCalendarRoute: AlysonNotetakerCalendarRoute,
  AlysonNotetakerCostTrackingRoute: AlysonNotetakerCostTrackingRoute,
  AlysonNotetakerMeetingListRoute: AlysonNotetakerMeetingListRoute,
  AlysonNotetakerTasksRoute: AlysonNotetakerTasksRoute,
  AlysonNotetakerUnifiedMeetingsRoute: AlysonNotetakerUnifiedMeetingsRoute,
  AlysonNotetakerIndexRoute: AlysonNotetakerIndexRoute,
}

const AlysonNotetakerRouteRouteWithChildren =
  AlysonNotetakerRouteRoute._addFileChildren(AlysonNotetakerRouteRouteChildren)

interface BonusRouteRouteChildren {
  BonusAnalyticsRoute: typeof BonusAnalyticsRoute
  BonusApprovalsRoute: typeof BonusApprovalsRoute
  BonusAuditRoute: typeof BonusAuditRoute
  BonusPlansRoute: typeof BonusPlansRoute
  BonusSimulateRoute: typeof BonusSimulateRoute
  BonusIndexRoute: typeof BonusIndexRoute
}

const BonusRouteRouteChildren: BonusRouteRouteChildren = {
  BonusAnalyticsRoute: BonusAnalyticsRoute,
  BonusApprovalsRoute: BonusApprovalsRoute,
  BonusAuditRoute: BonusAuditRoute,
  BonusPlansRoute: BonusPlansRoute,
  BonusSimulateRoute: BonusSimulateRoute,
  BonusIndexRoute: BonusIndexRoute,
}

const BonusRouteRouteWithChildren = BonusRouteRoute._addFileChildren(
  BonusRouteRouteChildren,
)

interface LeaveRouteRouteChildren {
  LeaveAnalyticsRoute: typeof LeaveAnalyticsRoute
  LeaveAuditRoute: typeof LeaveAuditRoute
  LeaveCalendarRoute: typeof LeaveCalendarRoute
  LeaveIndexRoute: typeof LeaveIndexRoute
}

const LeaveRouteRouteChildren: LeaveRouteRouteChildren = {
  LeaveAnalyticsRoute: LeaveAnalyticsRoute,
  LeaveAuditRoute: LeaveAuditRoute,
  LeaveCalendarRoute: LeaveCalendarRoute,
  LeaveIndexRoute: LeaveIndexRoute,
}

const LeaveRouteRouteWithChildren = LeaveRouteRoute._addFileChildren(
  LeaveRouteRouteChildren,
)

interface EmployeeScoringRouteChildren {
  EmployeeScoringUserEmailRoute: typeof EmployeeScoringUserEmailRoute
}

const EmployeeScoringRouteChildren: EmployeeScoringRouteChildren = {
  EmployeeScoringUserEmailRoute: EmployeeScoringUserEmailRoute,
}

const EmployeeScoringRouteWithChildren = EmployeeScoringRoute._addFileChildren(
  EmployeeScoringRouteChildren,
)

interface TimeDashboardRouteChildren {
  TimeDashboardUserIdRoute: typeof TimeDashboardUserIdRoute
  TimeDashboardMonthlyPacingRoute: typeof TimeDashboardMonthlyPacingRoute
  TimeDashboardPacingRoute: typeof TimeDashboardPacingRoute
}

const TimeDashboardRouteChildren: TimeDashboardRouteChildren = {
  TimeDashboardUserIdRoute: TimeDashboardUserIdRoute,
  TimeDashboardMonthlyPacingRoute: TimeDashboardMonthlyPacingRoute,
  TimeDashboardPacingRoute: TimeDashboardPacingRoute,
}

const TimeDashboardRouteWithChildren = TimeDashboardRoute._addFileChildren(
  TimeDashboardRouteChildren,
)

interface WorkspaceActivityRouteChildren {
  WorkspaceActivityUserEmailRoute: typeof WorkspaceActivityUserEmailRoute
}

const WorkspaceActivityRouteChildren: WorkspaceActivityRouteChildren = {
  WorkspaceActivityUserEmailRoute: WorkspaceActivityUserEmailRoute,
}

const WorkspaceActivityRouteWithChildren =
  WorkspaceActivityRoute._addFileChildren(WorkspaceActivityRouteChildren)

interface ApiAnalyticsEmployeeScoringRouteChildren {
  ApiAnalyticsEmployeeScoringUserEmailRoute: typeof ApiAnalyticsEmployeeScoringUserEmailRoute
}

const ApiAnalyticsEmployeeScoringRouteChildren: ApiAnalyticsEmployeeScoringRouteChildren =
  {
    ApiAnalyticsEmployeeScoringUserEmailRoute:
      ApiAnalyticsEmployeeScoringUserEmailRoute,
  }

const ApiAnalyticsEmployeeScoringRouteWithChildren =
  ApiAnalyticsEmployeeScoringRoute._addFileChildren(
    ApiAnalyticsEmployeeScoringRouteChildren,
  )

interface ApiAnalyticsUnifiedMeetingsRouteChildren {
  ApiAnalyticsUnifiedMeetingsRefreshRoute: typeof ApiAnalyticsUnifiedMeetingsRefreshRoute
  ApiAnalyticsUnifiedMeetingsScheduleBotsRoute: typeof ApiAnalyticsUnifiedMeetingsScheduleBotsRoute
  ApiAnalyticsUnifiedMeetingsMeetingIdScheduleRoute: typeof ApiAnalyticsUnifiedMeetingsMeetingIdScheduleRoute
  ApiAnalyticsUnifiedMeetingsMeetingIdUnscheduleRoute: typeof ApiAnalyticsUnifiedMeetingsMeetingIdUnscheduleRoute
}

const ApiAnalyticsUnifiedMeetingsRouteChildren: ApiAnalyticsUnifiedMeetingsRouteChildren =
  {
    ApiAnalyticsUnifiedMeetingsRefreshRoute:
      ApiAnalyticsUnifiedMeetingsRefreshRoute,
    ApiAnalyticsUnifiedMeetingsScheduleBotsRoute:
      ApiAnalyticsUnifiedMeetingsScheduleBotsRoute,
    ApiAnalyticsUnifiedMeetingsMeetingIdScheduleRoute:
      ApiAnalyticsUnifiedMeetingsMeetingIdScheduleRoute,
    ApiAnalyticsUnifiedMeetingsMeetingIdUnscheduleRoute:
      ApiAnalyticsUnifiedMeetingsMeetingIdUnscheduleRoute,
  }

const ApiAnalyticsUnifiedMeetingsRouteWithChildren =
  ApiAnalyticsUnifiedMeetingsRoute._addFileChildren(
    ApiAnalyticsUnifiedMeetingsRouteChildren,
  )

interface ApiAnalyticsWorkspaceActivityRouteChildren {
  ApiAnalyticsWorkspaceActivityUserEmailRoute: typeof ApiAnalyticsWorkspaceActivityUserEmailRoute
}

const ApiAnalyticsWorkspaceActivityRouteChildren: ApiAnalyticsWorkspaceActivityRouteChildren =
  {
    ApiAnalyticsWorkspaceActivityUserEmailRoute:
      ApiAnalyticsWorkspaceActivityUserEmailRoute,
  }

const ApiAnalyticsWorkspaceActivityRouteWithChildren =
  ApiAnalyticsWorkspaceActivityRoute._addFileChildren(
    ApiAnalyticsWorkspaceActivityRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlysonNotetakerRouteRoute: AlysonNotetakerRouteRouteWithChildren,
  BonusRouteRoute: BonusRouteRouteWithChildren,
  LeaveRouteRoute: LeaveRouteRouteWithChildren,
  AdminRoute: AdminRoute,
  AlysonBrainRoute: AlysonBrainRoute,
  AppRoute: AppRoute,
  AttendanceRoute: AttendanceRoute,
  AuthRoute: AuthRoute,
  BoardingRoute: BoardingRoute,
  DocumentsRoute: DocumentsRoute,
  EmployeeOnboardingRoute: EmployeeOnboardingRoute,
  EmployeeScoringRoute: EmployeeScoringRouteWithChildren,
  EquityRoute: EquityRoute,
  HandoverDocumentationRoute: HandoverDocumentationRoute,
  HelpRoute: HelpRoute,
  PayrollRoute: PayrollRoute,
  PerformanceRoute: PerformanceRoute,
  ReportsRoute: ReportsRoute,
  TeamRoute: TeamRoute,
  TimeDashboardRoute: TimeDashboardRouteWithChildren,
  WorkflowsRoute: WorkflowsRoute,
  WorkspaceActivityRoute: WorkspaceActivityRouteWithChildren,
  WebhooksRecallRoute: WebhooksRecallRoute,
  ApiAnalyticsEmployeeScoringRoute:
    ApiAnalyticsEmployeeScoringRouteWithChildren,
  ApiAnalyticsUnifiedMeetingsRoute:
    ApiAnalyticsUnifiedMeetingsRouteWithChildren,
  ApiAnalyticsWorkspaceActivityRoute:
    ApiAnalyticsWorkspaceActivityRouteWithChildren,
  ApiCronDailyReportsRoute: ApiCronDailyReportsRoute,
  ApiCronNotetakerTranscriptsRoute: ApiCronNotetakerTranscriptsRoute,
  ApiCronRecallCalendarSyncRoute: ApiCronRecallCalendarSyncRoute,
  ApiCronScheduledBotActivationRoute: ApiCronScheduledBotActivationRoute,
  ApiCronTimeDoctorTokenRoute: ApiCronTimeDoctorTokenRoute,
  ApiRecallCalendarCallbackRoute: ApiRecallCalendarCallbackRoute,
  ApiRecallCalendarConnectRoute: ApiRecallCalendarConnectRoute,
  ApiRecallCalendarStatusRoute: ApiRecallCalendarStatusRoute,
  ApiRecallWebhooksCalendarRoute: ApiRecallWebhooksCalendarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
